# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kJu1BSPocih2DwUlsyCUL8XDt6MtQyBc
"""

pip install openai

pip install --upgrade cohere tiktoken typing-extensions

pip install openai==0.28

import openai

# Set your OpenAI API key
api_key = 'YOUR API KEY'
openai.api_key = api_key

def generate_chat_response(prompt):
    response = openai.ChatCompletion.create(
        model="gpt-3.5-turbo",
        messages=[
            {"role": "system", "content": "You are a helpful assistant."},
            {"role": "user", "content": prompt}
        ]
    )

    return response['choices'][0]['message']['content']

# Example usage
user_input = "Tell me a joke about clouds."

# Generate a response
response = generate_chat_response(user_input)

print(response)

